### PR TITLE
Add bibtex and add entry to changelog

### PR DESCRIPTION
**Pull request by carlini**

### CODE REVIEW

**Review by anishathalye — APPROVED** [review]
LGTM

Semi-related: should we come up with some policy for how frequently to update the arXiv submission? E.g. the current arXiv submission is missing Alexey's name.

**Comment by carlini** [comment]
Yeah. I'm pushing a new arxiv update today to add his name -- I feel bad about missing that. But I agree that we should document when we will update the arxiv version of the paper, let's create an issue to discuss what a good process for that would be.

**Comment by anishathalye** [comment]
When you update the arXiv today, can you also add a note pointing back to this GitHub repo (I know it's in the paper, but it'll be nice to have it in the notes section of the arXiv submission too).

**Comment by carlini** [comment]
Done

**Pull request merged**
